[package]
name = "fix_in"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.25"
ndarray = "0.15.6"
ndarray-stats = "0.5.1"
once_cell = "1.17.0"
